harvard-lts/mps-viewer

docker-compose-local.yml

**Adding separate volume for js/dist folder.*
* * *
This adds a new docker volume for `/home/node/app/public/js/dist` This is so the local folder does not override the container folder. This way Webpack can be built correctly through Dockerfile and DockerfileLocal on container build.
*On the `main` branch, delete all the files in your local `/mps-viewer/public/js/dist` folder
* Build the container: `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`
* The mirador viewer should not load at all on the site in your browser.
* If you bash into the container (`docker exec -it mps-viewer bash`) and go to the `/home/node/app/public/js/dist` folder you will see it is still empty even though webpack was run successfully.
* …

Adding separate volume for js/dist folder.

---

public/js/netlify.js
public/netlify.html
public/viewer.html

**Adding ability to display any object in Netlify viewer.*
* * *
**JIRA Ticket**: [LTSVIEWER-82](https://jira.huit.harvard.edu/browse/LTSVIEWER-82)
This updates the netlify.html page to allow you to pass in request variables to display other objects besides the default.
* Rebuild the container.
* Go to this page and confirm that the Igor Stravinsky item appears: https://localhost:23017/netlify.html
* There are two request variables. `type` and `id`. You Can go to any object in Harvard Digital Collections, click on the "copy manifest link" and use the variables in the manifest url to build the request variables here.
* For example, this item in HDC: https://digitalcollections.library.harvard.edu/catalog/W595562_URN-3:HUL.ARCH:4906440 can …

Adding ability to display any object in Netlify viewer.

---

public/netlify.html

**Updating copyright date on netlify page.*
* * *
This just changes the copyright date in the footer of the Netlify page from 2021 to 2022.
* Rebuild the container.
* Go to the Netlify page and note that the copyright date is 2022: https://mps-viewer.netlify.app/netlify.html

Updating copyright date on netlify page.

---

.jshintrc
Dockerfile
DockerfileLocal
controllers/embed.ctrl
docker-compose.yml
env-example.txt
package-lock.json
package.json
routes/index.js
views/example.eta
views/index.eta

**Viewer example now completely uses mps-embed service.**
* * *
**JIRA Ticket**: [LTSVIEWER-102](https://jira.huit.harvard.edu/browse/LTSVIEWER-102)
This uses the mps-embed service to display the viewer in the example pages, instead of  using object type and object id from the request variables.
The path now expects the recordIdentifer which it the mps-embed service uses to return the JSON oEmbed response. The response is then used to embed the Viewer in an `<iframe>` on the page.
Additionally, something changed over the winter break with openssl and the lts-alpine Docker image. The `/etc/ssl/openssl.cnf` file has been moved to `/etc/ssl1.1/openssl.cnf`. If you build the container off of the `main` branch it will fail because it cannot find the file.
Finally, it adds new environment …

Viewer example now completely uses mps-embed service.

---

package-lock.json

**Updating follow-redirects package.**
* * *
**JIRA Ticket**: None
* [Dependabot Alert](https://github.com/harvard-lts/mps-viewer/security/dependabot/package-lock.json/follow-redirects/open)
This upgrades the follow-redirects package to 1.14.7, resolving the high severity alert found by dependabot.
* Build the container off of the `main` branch
* SSH into the container: `docker exec -it mps-viewer bash`
* Run `npm audit` and notice it is displaying the same alert as dependabot
* Take down and destroy the container and switch to the `update-follow-redirects` branch
* Build the container
* SSH into the container
* Run `npm audit` and notice that the alert is …

Updating follow-redirects package.

---

.github/workflows/test.yml
__tests__/a.test.js
__tests__/integration/healthchecks.test.js
__tests__/unit/embed.test.js
app.js
docker-compose.yml
jest.config.js
package-lock.json
package.json
routes/index.js

**Add passing tests. Add GitHub Action that runs unit tests.**
* * *
**JIRA Tickets**: [LTSVIEWER-103](https://jira.huit.harvard.edu/browse/LTSVIEWER-103) [LTSVIEWER-100](https://jira.huit.harvard.edu/browse/LTSVIEWER-100)
* Other Relevant Links:
- [MPS Asset Delivery Images Testing Scripts](https://github.huit.harvard.edu/LTS/mps-asset-delivery-images/blob/main/app/package.json#L9-L12)
- [MPS Asset Delivery Images Test Folder](https://github.huit.harvard.edu/LTS/mps-asset-delivery-images/tree/main/app/__tests__)
- [SysDev Automated Tests Wiki](https://wiki.harvard.edu/confluence/pages/viewpage.action?spaceKey=LibraryTechServices&title=SysDev+-+Automated+tests)
This PR adds Unit Tests and Integration Tests for Viewer. I based this off of the examples provided in the MPS Asset Delivery …

Add passing tests. Add GitHub Action that runs unit tests.

---

.github/workflows/test.yml

**Add Integration Tests to Github Actions*
* * *
This adds the integration tests to the Github Actions script. It uses embed-qa as the healthcheck test, via an environment variable.
* You could install Act (https://github.com/nektos/act) and confirm the Github Action runs successfully by running the `act` command.
* Or you could see the last action I ran for this branch successfully finished here: https://github.com/harvard-lts/mps-viewer/runs/4898648704?check_suite_focus=true
- unit tests? Yes
- integration tests? Yes
@enriquediaz

Add Integration Tests to Github Actions

---

docker-compose.yml
src/mirador.js
views/index.eta

**Turn on zoom. Add new item to index page.**
* * *
**JIRA Ticket**: [LTSVIEWER-118](https://jira.huit.harvard.edu/browse/LTSVIEWER-118)
This turns on the Zoom buttons to help with accessibility. It also adds a new item "Heures de Nôtre Dame (use of Troyes and Sens) : manuscript, [ca. 1470]" to the bottom of the index page.
* Rebuild the container using the `turn-on-zoom` branch
* Go to the index page (https://localhost:23017/) and see "Heures de Nôtre Dame (use of Troyes and Sens) : manuscript, [ca. 1470]" at the bottom of the list. 
* Click on "Heures de Notre Dame..." and confirm the item shows up in the viewer.
* Notice that the Zoom In / Zoom Out / Reset Zoom buttons are showing up by default in the viewer. 
Yes/No: Are changes in …

Turn on zoom. Add new item to index page.

---

plugins/hide_viewer_navigation.js

**Fixing query selectors.*
* * *
This adds a wildcard to the querySelector for the divider since the number at the end seems to change. I also set up the querySelector to work similarly for the pager and the title since it is a nice ES6 way of doing things.
* Rebuild the container using the delivery-type branch
* Confirm that the pager, divider and title do not show up for single images.
* Confirm that the pager, divider and title show up for paged items.
- unit tests? No 

Fixing query selectors.

---

docker-compose.yml
package-lock.json

**Upgrading node-fetch and follow-redirects.**
* * *
This upgrades node-fetch to 2.6.7 and follow-redirects to 1.14.9 because of dependabot alerts.
- https://github.com/harvard-lts/mps-viewer/security/dependabot/2
- https://github.com/harvard-lts/mps-viewer/security/dependabot/3
* Completely rebuild the container off of the `dependabot-fix` branch
* Confirm the application is still working correctly.

Dependabot fix

---

Dockerfile
DockerfileLocal

**Fixing openssl cert location.**
* * *
The location of the openssl.cnf file has moved back to `/etc/ssl/` from `/etc/ssl1.1/`. This PR updates the Dockerfiles so that the container can successfully build.
* Rebuild the container off of the `fix-openssl` branch
* Confirm the application builds successfully and is viewable in the browser.

Fixing openssl cert location.

---

package-lock.json

**Updating plugins to 1.0.1.**
* * *
As part of the on-call sprint, I upgraded node packages in our two custom plugins (mirador-help-plugin and mirador-hide-nav-plugin). This updates mps-viewer to use the latest versions of those plugins.
* Rebuild mps-viewer using the `update-hide` branch
* Make sure you are also running mps-embed locally
* ssh into the container: `docker exec -it mps-viewer bash`
* Confirm version 1.0.1 of mirador-help-plugin is installed: `npm list @harvard-lts/mirador-help-plugin`
* Confirm version 1.0.1 of mirador-hide-nav-plugin is installed: `npm list @harvard-lts/mirador-hide-nav-plugin`
* Go to https://localhost:23017/
* Confirm that …

Updating plugins to 1.0.1.

---

package-lock.json

**Updating mirador-help-plugin to 1.0.2..**
* * *
This updates the "report a problem" link in the help modal to use the proper URN.
* Rebuild mps-viewer using the `update-report-link` branch
* Make sure you are also running mps-embed locally
* ssh into the container: `docker exec -it mps-viewer bash`
* Confirm version 1.0.2 of mirador-help-plugin is installed: `npm list @harvard-lts/mirador-help-plugin`
* Go to https://localhost:23017/
* Confirm the URN is used for the "Report a Problem" link in the Help modal.
@enriquediaz

updating mirador-help-plugin to 1.0.2.

---

src/mirador.js

**JIRA Ticket**: [LTSVIEWER-180](https://jira.huit.harvard.edu/browse/LTSVIEWER-180)
Fixes an issue where when a manifest containing OCR is added to the viewer using the "Add resource" button results in an error message. The message says that 'Yellow' is not a valid colour option for a MUI component.
- On QA test adding this manifest: https://mps-dev.lib.harvard.edu/iiif/3/URN-3:HUL.OIS:101114808 (OIS tunnel required)
- On this branch, try adding the same manifest — it should not display the error
- unit tests? N/A
- integration tests? N/A
@ktamaral @enriquediaz

Change named colour values to hex equivalent

---

package-lock.json
package.json

**Updating mirador-pdiif-plugin to 0.1.4.**
* * *
**JIRA Ticket**: [(LTSVIEWER-183)](https://jira.huit.harvard.edu/browse/LTSVIEWER-183)
This updates the concurrency used in the pdiif convertManifest API call from 1 to 4. This significantly speeds up large downloads. This works together with [the Pull Request in mirador-pdiiif-plugin](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/3).
These changes have already been built to npmjs as **@harvard-lts/mirador-pdiiif-plugin 0.1.4**.
* Please see the speed differences I experienced in [this JIRA comment](https://jira.huit.harvard.edu/browse/LTSVIEWER-183?focusedCommentId=634865&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-634865). You should see …

Updating mirador-pdiif-plugin to 0.1.4.

---

healthcheck

**JIRA Ticket**: [LTSVIEWER-157](https://jira.huit.harvard.edu/browse/LTSVIEWER-157)
Adds an executable which can be used instead of curl to verify that the healthcheck endpoint is reachable
My understanding is that this will be used by CI in some way in the future. But to test this now locally, you should be able to verify that from project root directory (while the embed service is running):
From your host machine:
- Running `./healthcheck https://localhost:23017/healthcheck` => `HEALTHCHECK STATUS: 200`
- Running `./healthcheck https://localhost:23017/healthcheck-random-string` => `HEALTHCHECK STATUS: 404`
From the container (using `docker exec -it mps-viewer bash`):
- Running `./healthcheck https://mps-viewer:8081/healthcheck` => `HEALTHCHECK STATUS: 200`
- Running `./healthcheck …

Add healthcheck executable

---

.gitignore
package-lock.json
package.json
public/pdiiif/mitm.html
public/pdiiif/sw.js
src/mirador.js

**JIRA Ticket**: [LTSVIEWER-172](https://jira.huit.harvard.edu/browse/LTSVIEWER-172)
This just updates the dependency for the PDIIIF plugin to the latest tag and provides access to a `mitm.html` for streamsaver. [The companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/4) for this has further details about these changes.
- For full instructions see the [companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/4) as that contains detailed instructions that apply here as well
@enriquediaz

Update mirador-pdiiif-plugin and add config for PDIIIF

---

.dockerignore
.gitignore
README.md
config/example-items-example.txt
controllers/examples.ctrl.js
docker-compose-local.yml
routes/index.js

**Make example items environment specific.**
* * *
**JIRA Ticket**: [LTSVIEWER-184](https://jira.huit.harvard.edu/browse/LTSVIEWER-184)
This updates the index page to use an external json file to determine what shows up in both the IDS and MPS examples list. You need to manually add the `config/example-items.json` file to your filesystem before spinning up the containers. Also note the new variables in the .env file to determine what environment it will use for MPS.
I have attached 3 files in a zip file to this PR that you can use for each environment.
[ExampleItems.zip](https://github.com/harvard-lts/mps-viewer/files/11547403/ExampleItems.zip)
* Unzip the `ExampleItems.zip` file attached to this PR.
* Rename `example-items-dev.json` to …

Make example items environment specific

---

package-lock.json
package.json

**JIRA Ticket**: [LTSVIEWER-158](https://jira.huit.harvard.edu/browse/LTSVIEWER-158)
- [Harvard LTS PDIIIF companion PR](https://github.com/harvard-lts/pdiiif/pull/1)
- [PDIIIF Mirador Plugin companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/8)
Updates PDIIIF Mirador Plugin to a version which allows the coverpage API endpoint to be passed in as config.
- Refer to the testing instructions in the [Harvard LTS PDIIIF repository](https://github.com/harvard-lts/pdiiif/pull/1)
@enriquediaz

Add configurable coverpage endpoint

---

package-lock.json
package.json

**JIRA Ticket**: LTSVIEWER-197
- [PDIIIF mirador plugin companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/9)
Updates the PDIIIF mirador plugin version to lower the acceptable suggested file name length.
- See the [companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/9) for full test instructions

Update PDIIIF to lower chara limit

---

package-lock.json
package.json

**JIRA Ticket**: [LTSVIEWER-178](https://jira.huit.harvard.edu/browse/LTSVIEWER-178)
- [PDIIIF Mirador plugin companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/10)
Updates the version of the PDIIIF plugin to include the progress bar and cancel button features.
- See the [companion PR](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/10) for full testing instructions 
- unit tests? N/A
- integration tests? N/A
@enriquediaz

Add progress bar and cancel button

---

docs/developing-mirador-plugins.md
package-lock.json
package.json

**JIRA Ticket**: [LTSVIEWER-228](https://jira.huit.harvard.edu/browse/LTSVIEWER-228)
- [PR for PDIIIF plugin](https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/12)
Updates documentation to cover recent updates and improvements into the workflow for the PDIIIF plugin. Some of this overlaps with the plugin linked above.
It also includes a version update for the PDIIIF plugin which was generated with the new workflow.
- Check the documentation for errors
- Check the plugin works with the included version
@enriquediaz

Update docs about workflow and publishing plugins

---

env-example.txt
package-lock.json
package.json
src/mirador.js
webpack/webpack.config.js

**Adding ability to switch between pdiiif endpoints.**
* * *
**JIRA Ticket**: [LTSVIEWER-221](https://jira.huit.harvard.edu/browse/LTSVIEWER-221)
This updates the application to use a new .env variable called `PDIIIF_COVERPAGE_ENDPOINT` to determine which pdiiif endpoint to use for generating the coverpages.
* Add the new `PDIIIF_COVERPAGE_ENDPOINT` variable to your local `.env` file.
* Dev value of the endpoint is: https://pdiiif-dev.lib.harvard.edu/api/coverpage
* QA value of the endpoint is: https://pdiiif-qa.lib.harvard.edu/api/coverpage 
* Rebuild the container using the `LTSVIEWER-221b` branch
* Go to any item and download the PDF
* If you inspect the network you should see that it uses whatever endpoint you set in the `.env` to …

Adding ability to switch between pdiiif endpoints.

---

Dockerfile
bin/webpack.sh
docker-compose-local.yml

**Moving webpack to entrypoint.**
* * *
**JIRA Ticket**: [LTSVIEWER-239](https://jira.huit.harvard.edu/browse/LTSVIEWER-239)
This moves webpack from being run as root as the same time as npm install to being run by the mpsadmin user everytime the container is restarted. This will allow the LTS cloud environments to use the .env variable to switch coverpage endpoints.
* Rebuild the container from the `LTSVIEWER-239` branch
* Confirm that webpack ran successfully after the container was build (`docker logs -f mps-viewer`)
* Take the container down: docker-compose -f docker-compose-local.yml down 
* Bring the container back up (without rebuilding): docker-compose -f docker-compose-local.yml up -d
* Confirm that webpack ran successfully again …

Moving webpack to entrypoint.

---

plugins/harvard_branding.js

**Update Harvard shield for accessibility**
* * *
**JIRA Ticket**: [LTSVIEWER-229](https://jira.huit.harvard.edu/browse/LTSVIEWER-229)
Removed link and added a blank alt-text tag to the Harvard shield so that Viewer is compliant with accessibility standards and more generic for use across the university
* Spin up Viewer from this branch
* Inspect the Harvard shield in the lower left corner of Viewer; you should notice that the image has a blank alt-text tag (alt="") and that it is no longer enclosed by a link tag
* Tab through the page; since the shield is no longer a link, it should be skipped when tabbing
* On a mac, open up voiceover and head to the rotor view (CMD+OPT+U); the shield should not show up in the links window as an option
Yes/No: Are changes in this pull-request covered …

Update Harvard shield for accessibility

---

README.md
docs/community-mirador-plugins.md

**Adding community mirador plugins to README.**
* * *
**JIRA Ticket**: [LTSVIEWER-215](https://jira.huit.harvard.edu/browse/LTSVIEWER-215)
This adds a new page to the README table of contents which lists the community plugins we are using in MPS Viewer.
* Pull in the latest code from the LTSVIEWER-215 branch
* Confirm that the new item in the Table of Contents works and makes sense.
@f8f8ff

Adding community mirador plugins to README.

---

views/template.eta
views/viewer.eta

**Include 50 characters of citation in <title> element**
* * *
**JIRA Ticket**: [LTSVIEWER-234](https://jira.huit.harvard.edu/browse/LTSVIEWER-234)
Adds the citation title into the tab; also truncates to the first 50 characters of the citation so that the tab text isn't too long
* Spin up Viewer from this branch
* From the homepage, you'll notice the tab title reads “Welcome to the MPS Viewer! - Mirador Viewer”
* If you click on an item with more than 50 characters, such as Chronique du monde, that item's tab title reads "Chronique du monde depuis la création, et des rois - MPS Viewer"
* If you click on an item with 50 characters or less, such as the baseball photograph (which is right at 50 characters), that item's tab title reads …

Include 50 characters of citation in <title> element

---

docs/developing-mirador-plugins.md
package-lock.json
package.json

**Updating mirador-help-plugin to 1.0.0**
* * *
**JIRA Ticket**: [LTSVIEWER-244](https://jira.huit.harvard.edu/browse/LTSVIEWER-244)
* PR with the plugin work: https://github.com/harvard-lts/mirador-help-plugin/pull/10
Pulls in the newest version of mirador-help-plugin, v1.0.0.
These changes have already been built to npmjs as [@harvard-lts/mirador-help-plugin 1.0.0](https://www.npmjs.com/package/@harvard-lts/mirador-help-plugin).
* Spinup viewer from this branch
* Navigate to the help modal window
* Window should reflect the newest version of the help plugin, which only contains 2 links
@enriquediaz

Updating mirador-help-plugin to 1.0.0

---

package-lock.json
package.json

**Update mirador-share-plugin version to 0.12.0**
* * *
**JIRA Tickets**: 
* [LTSVIEWER-242: Differentiate "Copy" labels in Share dialog](https://jira.huit.harvard.edu/browse/LTSVIEWER-242)
* [LTSVIEWER-243: Add descriptive label to form field in Share dialog](https://jira.huit.harvard.edu/browse/LTSVIEWER-243)
* PR with the plugin work: https://github.com/ProjectMirador/mirador-share-plugin/pull/47
Pulls in the newest version of mirador-share-plugin, v0.12.0.
These changes have already been built to npmjs as [@harvard-lts/mirador-share-plugin 0.12.0](https://www.npmjs.com/package/mirador-share-plugin).
* Spin up viewer from this branch
* Navigate to the share …

Update mirador-share-plugin version to 0.12.0

---

controllers/embed.ctrl.js
public/css/compiled/style.min.css
public/netlify.html
routes/index.js
views/example.eta
views/header.eta
views/index.eta
views/intro-message.eta
views/template.eta
views/viewer.eta

**Updating the site design to the Beta Viewer mockups.**
* * *
**JIRA Ticket**: [LTSVIEWER-263](https://jira.huit.harvard.edu/browse/LTSVIEWER-263)
This updates the site design to look like the mockups in LTSVIEWER-263.
* **FIRST: Make sure you are running mps-embed locally using the `LTSVIEWER-263` branch there!** See this PR: https://github.com/harvard-lts/mps-embed/pull/34
* Rebuild the mps-viewer container using the `LTSVIEWER-263` branch
* Confirm that the site matches the mockups in LTSVIEWER-263. Things that are changed include:
* The header is now blue instead of aqua.
* The header now says `BETA Viewer` instead of `MPS Viewer`
* The Mirador viewer now takes up 100% of the width of the page.
* Above the Mirador viewer there …

Updating the site design to the Beta Viewer mockups.

---

controllers/embed.ctrl.js
routes/index.js

**Adding new /manifest/ route to viewer for use with CURIOSity.**
* * *
**JIRA Ticket**: [LTSVIEWER-263](https://jira.huit.harvard.edu/browse/LTSVIEWER-263)
This adds a new route to mps-viewer at /manifest/ that allows you to pass in any Manifest URL.
* FIRST rebuild the mps-embed container using the LTSVIEWER-263 branch
* Rebuild the mps-viewer container using the LTSVIEWER-264 branch
* Go to this url: https://localhost:23017/example/manifest/?manifestId=[manifestId] where [manifestId] can be the URL of any Manifest. For example: https://localhost:23017/example/manifest/?manifestId=https://iiif.lib.harvard.edu/manifests/drs:8282494
* You should see the item from the manifest displayed in the Mirador 3 viewer.
Yes/No: Are changes in this …

Adding new /manifest/ route to viewer for use with CURIOSity.

---

package-lock.json
package.json

**Upgrading mirador-pdiiif-plugin to 0.1.28.**
* * *
**JIRA Ticket**: [LTSVIEWER-270](https://jira.huit.harvard.edu/browse/LTSVIEWER-270)
Related PR for the mirador-pdiiif-plugin: https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/16
The PDF Download dialog box shows 0 bytes, because the plugin is expecting a number, but in mps-viewer it is actually getting an object. The object looks like this:
`Object { size: 502949479.7601479, corsSupported: true }`
* Build the mps-embed container off of the `main` branch
* Build the mps-viewer container off of the `LTSVIEWER-270` branch
* Confirm that the bytes are showing up properly for all examples in mps-viewer. …

Upgrading mirador-pdiiif-plugin to 0.1.28.

---

.gitignore
README.md
config/example-items-dev.json
config/example-items-example.txt
config/example-items-prod.json
config/example-items-qa.json
controllers/embed.ctrl.js
public/css/compiled/style.min.css
routes/index.js
views/index.eta

**Adding prod argument to API call. Updating homepage template for examples.**
* * *
**JIRA Ticket**: [LTSVIEWER-271](https://jira.huit.harvard.edu/browse/LTSVIEWER-271)
This adds a prod argument to API calls. This allows the homepages to mix both dev/qa examples and production examples. 
1. Copy the contents of `example-items-dev.json` into your `example-items.json` file.
2. Rebuild the mps-viewer container using the `LTSVIEWER-271` branch
3. Go to the homepage and confirm you see Dev and Production items under the MPS Examples heading, along with new information for each item including owner, object type, size and environment. 
4. Click on each item and confirm the json response shows up properly.
5. Repeat steps 2-4 using the QA and …

Adding prod argument to API call. Updating homepage template for examples.

---

config/example-items-dev.json
config/example-items-prod.json
config/example-items-qa.json

**Adding new production PTO examples.**
* * *
**JIRA Ticket**: [LTSVIEWER-271](https://jira.huit.harvard.edu/browse/LTSVIEWER-271)
This updates the "Production" example items in each environment to use the following examples:
-     https://mps.lib.harvard.edu/iiif/3/URN-3:DIV.LIB:29999858 3-page PTO in production, post-fix, no transcription
-     https://mps.lib.harvard.edu/iiif/3/URN-3:HLS.LIBR:102621314 121-page PTO in production, post-fix, with transcriptions
-     https://mps.lib.harvard.edu/iiif/3/URN-3:GSE.LIBR:42470991 468-page PTO in production, post-fix, spanish, transcription
-     https://mps.lib.harvard.edu/iiif/3/URN-3:RAD.SCHL:101557499 725-page PTO in production, post-fix, partial transcripts
These examples have been re-ingested by MPS so they have both Version 2 and …

Adding new production PTO examples.

---

config/example-items-dev.json
config/example-items-prod.json
config/example-items-qa.json
controllers/embed.ctrl.js
views/index.eta

**Adding new nrs route and updating examples.**
* * *
**JIRA Ticket**: [LTSVIEWER-261](https://jira.huit.harvard.edu/browse/LTSVIEWER-261)
This adds a new route at /example/nrs/. It allows you to pass in a URN and then it uses NRS to get the IIIF Manifest and Viewer. At this time NRS will always return a Mirador 2 Viewer.
* Bring up mps-embed on the LTSVIEWER-261 following the instructions in this PR: https://github.com/harvard-lts/mps-embed/pull/40
* Update your `example-items.json` file using the desired environment. The environment needs to match what is running in mps-embed.
* Bring up mps-viewer using the `LTSVIEWER-261` branch.
* Go to the homepage and confirm that the new NRS links for each item bring up a working Mirador2 Viewer …

Adding new nrs route and updating examples.

---

config/example-items-dev.json
config/example-items-qa.json

**Removing non-production NRS links.**
* * *
**JIRA Ticket**: [LTSVIEWER-261](https://jira.huit.harvard.edu/browse/LTSVIEWER-261)
Since the IDS / PDS environments are unstable in Dev and QA, the "NRS" links for items have been removed for those environments. The link only shows up for MPS examples tagged as "Prod". Along with mps-embed PR-41 (https://github.com/harvard-lts/mps-embed/pull/41) this also fixes NRS static Images. They now show up in the Mirador 2 viewer.
* Rebuild mps-embed off of the `LTSVIEWER-261b` branch with either the dev or qa example file.
* Rebuild mps-viewer off of the `LTSVIEWER-261b` branch with either the dev or qa example file.
* Confirm that "NRS" links only show up for MPS Examples tagged as "Prod"
* Confirm …

Removing non-production NRS links.

---

package-lock.json
package.json

**Upgrade mirador-help-plugin to 1.2.0**
* * *
**JIRA Ticket**: [LTSVIEWER-92](https://jira.huit.harvard.edu/browse/LTSVIEWER-92)
* PR with the plugin work: https://github.com/harvard-lts/mirador-help-plugin/pull/12
Renames the self-help documentation link and updates it to point to the LibAnswers knowledge base article
These changes have already been built to npmjs as [@harvard-lts/mirador-help-plugin 1.2.0](https://www.npmjs.com/package/@harvard-lts/mirador-help-plugin).
* Spin up viewer from this branch
* Open the "Help" modal window
* Confirm that the first list item reads "Using the Viewer" and points to https://ask.library.harvard.edu/faq/392399
- unit …

Upgrade mirador-help-plugin to 1.2.0

---

package-lock.json
package.json

**Upgrade mirador-pdiiif-plugin to 0.1.29**
* * *
**JIRA Ticket**: [LTSVIEWER-227](https://jira.huit.harvard.edu/browse/LTSVIEWER-227)
* Other Relevant Links
* PR with the plugin work: https://github.com/harvard-lts/mirador-pdiiif-plugin/pull/17
Disables page range input field when download is complete.
These changes have already been built to npmjs as [@harvard-lts/mirador-pdiiif-plugin 0.1.29](https://www.npmjs.com/package/@harvard-lts/mirador-pdiiif-plugin).
- Spin up viewer from this branch
- Open the "Download PDF" modal window (a dropdown option under the three dots in the top right of viewer)
- Begin a download and confirm that the page range input field is disabled both during the download and after the download has completed
- Close the modal window and reopen it
- Confirm that …

Upgrade mirador-pdiiif-plugin to 0.1.29

---

routes/index.js

**Adding height and width request variables.**
* * *
**JIRA Ticket**: [LTSVIEWER-284](https://at-harvard.atlassian.net/browse/)
This adds the ability to customize the height and width of the viewer that is displayed on the example pages using request variables. 
* Spin up `mps-embed` off of the `main` branch
* Spin up `mps-viewer` off of the `LTSVIEWER-284` branch
* Go to any example page and the Viewer should display full screen (the same as before)
* Adding `height` and `width` to the end of the url will adjust the size of the viewer. For example: https://localhost:23017/example/mps/URN-3:HUL.GUEST:409464?manifestVersion=3&height=700&width=1200
* I believe `height=700` and `width=1200` was the previous default size for Viewer so we …

Adding height and width request variables.

---

controllers/embed.ctrl.js
public/css/compiled/style.min.css
routes/index.js
views/example.eta

**Adding style to account for embed always returning 100% height and 100% width.**
* * *
**JIRA Ticket**: [LTSVIEWER-274](https://at-harvard.atlassian.net/browse/LTSVIEWER-274)
This updates the stylesheet and api calls to mps-embed to account for the fact that mps-embed always returns height=100% and width=100% in the iframe tag.
* Rebuild `mps-embed` off of the `LTSVIEWER-274` branch first!
* Rebuild `mps-viewer` off of the `LTSVIEWER-274` branch.
* Go to any link on the homepage. The viewer should display with full width and 700px height.
* If you adjust the zoom in your browser, the viewer controls still completely display and are accessible.
* The unit tests still pass.  In the container you can run `npm run test` and see them all …

Adding style to account for embed always returning 100% height and 100% width.

---

.gitignore
app.js
env-example.txt
logger/logger.js
package-lock.json
package.json

**Adding ability to turn off file logging.**
* * *
* 
This adds a new environment variable `LOG_TO_STDOUT` which allows you to toggle the saving of the logs to a file. The format of the file logging is also changed slightly to match what is in the `node-ci-template` repository (see: https://github.com/harvard-lts/node-ci-template).
* Add the `LOG_TO_STDOUT` variable to your local `.env` file. Set it to `false`.
* Rebuild the container from the `stdout-log` branch
* Click around on the site and confirm that the logging is displaying in stdout as well as in files on your local computer.
* Take down the container and change the `LOG_TO_STDOUT` variable to `true`
* Rebuild the container
* Click around on the site and confirm that the logging …

Adding ability to turn off file logging.

---

controllers/embed.ctrl.js
controllers/http.ctrl.js
routes/index.js

**Fixing undefined error messages.**
* * *
Some error messages were just displaying a message that said "undefined" instead of something more helpful. This fixes it so the messages are helpful.
* Rebuild mps-viewer off of the `fix-error-message` branch
* Do not have mps-embed running locally.
* Attempt to go to any example item in mps-viewer.
* An actual error message should appear in the log.

Fixing undefined error messages.
